dist: xenial

language: go

go:
  - "1.12.x"

branches:
  only:
    - master

install:
  - git clone https://github.com/elastic/go-langserver $GOPATH/src/golang.org/x/tools
  - cd $GOPATH/src/golang.org/x/tools

git:
  depth: 1

env:
  - GO111MODULE=off GOPROXY=https://proxy.golang.org


before_install:
  - go get golang.org/x/sync/errgroup

script:
  - set -e
  - go test -v ./internal/lsp
  - go build -o go-langserver $GOPATH/src/golang.org/x/tools/cmd/gopls

matrix:
  include:
    - name: Unit Tests & Package | Linux, gomod=on
      os: linux
      after_script:
        - curl -O https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
        - tar xvzf go1.12.7.linux-amd64.tar.gz

    - name: Unit Tests & Package | OSX, gomod=on
      os: osx
      after_script:
        - curl -O https://dl.google.com/go/go1.12.7.darwin-amd64.tar.gz
        - tar xvzf go1.12.7.darwin-amd64.tar.gz
