dist: xenial

language: go

go:
  - "1.12.x"

branches:
  only:
    - master

install:
  - git clone https://github.com/elastic/go-langserver $GOPATH/src/golang.org/x/tools
  - cd $GOPATH/src/golang.org/x/tools

git:
  depth: 1

env:
  - GO111MODULE=off GOPROXY=https://proxy.golang.org


before_install:
  - go get golang.org/x/sync/errgroup

matrix:
  fast_finish: true
  include:
    - name: Unit Tests & Package | Linux
      os: linux
      script:
        - go test ./internal/lsp
        - go build -o ../go-langserver-linux-amd64 $GOPATH/src/golang.org/x/tools/cmd/gopls
        - curl -o ../go1.12.7.linux-amd64.tar.gz https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
        - tar xzf ../go1.12.7.linux-amd64.tar.gz -C ../
        - rm ../go/bin/godoc & rm ../go/bin/gofmt & rm ../go/misc/benchcmp & rm ../go/misc/nacl/go_nacl* & rm -r ../go/pkg/tool/linux_amd64
        - mkdir build
        - tar -zcf ./build/go-langserver-linux-amd64.tar.gz ../go-langserver-linux-amd64 ../go
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        verbose: true
        local_dir: $GOPATH/src/golang.org/x/tools/build
        target_branch: linux_deploy
        on:
          branch: master

    - name: Unit Tests & Package | OSX
      os: osx
      script:
        - go test ./internal/lsp
        - go build -o ../go-langserver-darwin-amd64 $GOPATH/src/golang.org/x/tools/cmd/gopls
        - curl -o ../go1.12.7.darwin-amd64.tar.gz https://dl.google.com/go/go1.12.7.darwin-amd64.tar.gz
        - tar xzf ../go1.12.7.darwin-amd64.tar.gz -C ../
        - rm ../go/bin/godoc & rm ../go/bin/gofmt & rm ../go/misc/benchcmp & rm ../go/misc/nacl/go_nacl* & rm -r ../go/pkg/tool/darwin_amd64
        - mkdir build
        - tar -zcf ./build/go-langserver-darwin-amd64.tar.gz ../go-langserver-darwin-amd64 ../go
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        verbose: true
        local_dir: $GOPATH/src/golang.org/x/tools/build
        target_branch: darwin_deploy
        on:
          branch: master
