dist: xenial

language: go

go:
  - "1.12.x"

branches:
  only:
    - master

install:
  - git clone https://github.com/elastic/go-langserver $GOPATH/src/golang.org/x/tools
  - cd $GOPATH/src/golang.org/x/tools

git:
  depth: 1

env:
  - GO111MODULE=off GOPROXY=https://proxy.golang.org
  global:
    - secure: yde6nXZ8GhllLNN3O5ZqTlQJggynk3T+6I64kUogL+blXtJXoBKGWQTjrSWqnr/iK6w5Zukmx8d5FePQKZoZnllE+Hez94jonURf7Vc4tebfm/4y4wO+K0WBvNNzISnR5VBWXBTJntTuBKe6xnn7UALPxyKNuxfkmfd+OpO4wBh3Nw5/+SDnVtBvh4ALauL/WdMHk/Vr8Nhlb2niCokK2Yd2dZSrciTXAk6o1KJNETyVicn2YLQBb6/IKbTds4rSkmKGpUGbcmQOR8YRpFrmRvtGvHleRUnkorg8sEo0QtFCl/5AynL015x5CnceqSRBzCTKHYCpJOIkqGAa/WuAovorDSyBnS/VuhqteCTaoU5Vul8DhuUlggHorBzh6C0rsRFOryQN/J2wIkp5kb5N6cMIcA34HfcznsxoGLXgQFEfZdCHU4a9F6rTmcFGu4icwIE1BJPRhWIpPqHWg5KQYVDmPiNzHwjddGuL0qXSjbFHa4X0Utm4TSNPdX0P1xGaUjelfPXfe/hFOtZcrfGq+Y1TCp0uBKrnJUv1Mp6wG1T9KYn7ZvThM5rJK+VpZweH+fVWxIK0+8tQTp0fZCUPO2W+r+kAqfOc3XKCiIqp9HxfHTun3ILpwCPen+H2Mvdo9hnwF6tipoAwcmg3/zrOybFgDhVB62y1oW6jkjOhCVY=


before_install:
  - go get golang.org/x/sync/errgroup

matrix:
  include:
    - name: Unit Tests & Package | Linux
      os: linux
      script:
        - set -e
        - go test ./internal/lsp
        - go build -o ../go-langserver $GOPATH/src/golang.org/x/tools/cmd/gopls
      after_script:
        - cd ..
        - curl -O https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
        - tar xzf go1.12.7.linux-amd64.tar.gz
        - tar -zcf go-langserver-linux-amd64.tar.gz go-langserver go
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: go-langserver-linux-amd64.tar.gz
        on:
          branch: master

    - name: Unit Tests & Package | OSX
      os: osx
      script:
        - set -e
        - go test ./internal/lsp
        - go build -o ../go-langserver $GOPATH/src/golang.org/x/tools/cmd/gopls
      after_script:
        - curl -o ../go1.12.7.darwin-amd64.tar.gz https://dl.google.com/go/go1.12.7.darwin-amd64.tar.gz
        - tar xzf ../go1.12.7.darwin-amd64.tar.gz -C ../
        - tar -zcf go-langserver-darwin-amd64.tar.gz ../go-langserver ../go
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: go-langserver-darwin-amd64.tar.gz
        on:
          branch: master

    - name: Unit Tests & Package | Windows
      os: windows
      script:
        - set -e
        # TODO(henrywong) fix the test failures on windows and enable the test.
        # - go test ./internal/lsp
        - go build -o ../go-langserver $GOPATH/src/golang.org/x/tools/cmd/gopls
      after_script:
        - cd ..
        - curl -O https://dl.google.com/go/go1.12.7.windows-amd64.zip
        - dir
        - 7z x go1.12.7.windows-amd64.zip -o.
        - 7z a -r go-langserver-windows-amd64.zip go-langserver go
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: go-langserver-windows-amd64.zip
        on:
          branch: master
